apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/charanchelloju/orders-platform.git
    targetRevision: main
    path: helm/keycloak-ingress
    helm:
      releaseName: keycloak-ingress
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
