# ─── Keycloak IdP (OAuth2/OIDC for the platform) ──────────────────────────
# Open source identity provider. Backs Spring Security resource server
# config in each microservice. Same standard as Azure AD / Okta — swapping
# IdPs later is a one-line spring.security.oauth2.resourceserver.jwt
# .issuer-uri change.
#
# Path: served at <alb>/auth/* via the shared ALB.
# Storage: in-cluster Postgres (separate from app RDS) provided by the
#          Bitnami chart. Demo-grade — production would point at managed RDS.
# Admin credentials: generated by Terraform, stored in Secrets Manager,
#                    synced into K8s via ESO. Never committed to git.

resource "kubernetes_namespace" "keycloak" {
  metadata { name = "keycloak" }
  depends_on = [module.eks]
}

# Public hostname inside JWT issuer claim and JWKS URL.
locals {
  keycloak_alb_dns = "k8s-ordersplatform-e8323cc06c-1834496908.ap-south-1.elb.amazonaws.com"
}

# ─── Admin password — generated, stored in Secrets Manager ───────────────
resource "random_password" "keycloak_admin" {
  length           = 24
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "keycloak_admin" {
  name                    = "${var.project}/keycloak/admin"
  description             = "Keycloak admin user password"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "keycloak_admin" {
  secret_id = aws_secretsmanager_secret.keycloak_admin.id
  secret_string = jsonencode({
    admin-user     = "admin"
    admin-password = random_password.keycloak_admin.result
  })
}

# Grant ESO permission to read the Keycloak admin secret too
resource "aws_iam_role_policy" "eso_keycloak" {
  name = "eso-read-keycloak-secret"
  role = aws_iam_role.eso.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "secretsmanager:GetSecretValue",
        "secretsmanager:DescribeSecret",
      ]
      Resource = aws_secretsmanager_secret.keycloak_admin.arn
    }]
  })
}

# K8s ExternalSecret — ESO syncs the AWS secret into K8s `keycloak-admin`
# secret with keys `admin-user` and `admin-password`. The Bitnami chart
# expects exactly these key names via auth.existingSecret.
resource "kubernetes_manifest" "keycloak_admin_external_secret" {
  manifest = {
    apiVersion = "external-secrets.io/v1beta1"
    kind       = "ExternalSecret"
    metadata = {
      name      = "keycloak-admin"
      namespace = kubernetes_namespace.keycloak.metadata[0].name
    }
    spec = {
      refreshInterval = "1h"
      secretStoreRef = {
        name = "aws-secrets-manager"
        kind = "ClusterSecretStore"
      }
      target = {
        name = "keycloak-admin"
      }
      data = [
        {
          secretKey = "admin-user"
          remoteRef = {
            key      = aws_secretsmanager_secret.keycloak_admin.name
            property = "admin-user"
          }
        },
        {
          secretKey = "admin-password"
          remoteRef = {
            key      = aws_secretsmanager_secret.keycloak_admin.name
            property = "admin-password"
          }
        },
      ]
    }
  }

  depends_on = [
    aws_secretsmanager_secret_version.keycloak_admin,
    aws_iam_role_policy.eso_keycloak,
  ]
}

resource "helm_release" "keycloak" {
  name       = "keycloak"
  namespace  = kubernetes_namespace.keycloak.metadata[0].name
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "keycloak"
  version    = "21.4.4"

  timeout = 900

  values = [
    yamlencode({
      # Read admin credentials from the K8s secret created by ESO above
      auth = {
        existingSecret         = "keycloak-admin"
        passwordSecretKey      = "admin-password"
        adminUser              = "admin" # username is non-sensitive
      }

      httpRelativePath = "/auth/"

      extraEnvVars = [
        { name = "KC_HOSTNAME", value = local.keycloak_alb_dns },
        { name = "KC_HOSTNAME_STRICT", value = "false" },
        { name = "KC_HOSTNAME_STRICT_HTTPS", value = "false" },
        { name = "KC_PROXY", value = "edge" },
        { name = "KC_HTTP_ENABLED", value = "true" },
        { name = "JAVA_OPTS_KC_HEAP", value = "-Xms128m -Xmx384m" },
      ]

      replicaCount = 1

      resources = {
        requests = { cpu = "100m", memory = "384Mi" }
        limits   = { cpu = "800m", memory = "768Mi" }
      }

      service = { type = "ClusterIP" }
      ingress = { enabled = false }

      postgresql = {
        enabled = true
        auth = {
          username = "keycloak"
          password = "keycloak" # demo-only — in prod use ESO for this too
          database = "keycloak"
        }
        primary = {
          resources = {
            requests = { cpu = "50m", memory = "128Mi" }
            limits   = { cpu = "200m", memory = "256Mi" }
          }
          persistence = { size = "2Gi" }
        }
      }
    })
  ]

  depends_on = [
    kubernetes_manifest.keycloak_admin_external_secret,
    helm_release.alb_controller,
  ]
}

output "keycloak_issuer_uri" {
  value       = "http://${local.keycloak_alb_dns}/auth/realms/orders"
  description = "Spring config: spring.security.oauth2.resourceserver.jwt.issuer-uri"
}

output "keycloak_admin_url" {
  value       = "http://${local.keycloak_alb_dns}/auth/admin/master/console/"
  description = "Login here with admin + password from Secrets Manager"
}

output "keycloak_admin_password_cmd" {
  value       = "aws secretsmanager get-secret-value --region ${var.aws_region} --secret-id ${var.project}/keycloak/admin --query SecretString --output text | jq -r .[\\\"admin-password\\\"]"
  description = "Run this to fetch the generated Keycloak admin password"
}
