{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.secretName }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: SPRING_DATASOURCE_URL
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: SPRING_DATASOURCE_PASSWORD
{{- end }}
